miniblog/miniblog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from miniblog import settings
from stock.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stock.urls')),
]

handler404 = pageNotFound

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miniblog/stock/urls.py
from django.urls import path, re_path
from .views import *
from . import views

urlpatterns = [
    path('', index, name='home'),
    path('about/', about, name='about'),
    path('add_page/', add_page, name='add_page'),
    path('contact/', contact, name='contact'),
    path('login/', login, name='login'),
    path('<int:post_id>/', show_post, name='post'),
    path('category/<int:cat_id>/', show_category, name='category'),
    path('review/<int:post_id>/', views.AddComment.as_view(), name='add_comment'),
    path('<int:post_id>/add_likes/', views.AddLike.as_view(), name='add_likes'),
    path('<int:post_id>/del_likes/', views.DelLike.as_view(), name='del_likes')
]

miniblog/stock/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    '''Класс для категории вещей, первичный по отношению к классу Artifact'''
    name = models.CharField(max_length=100, db_index=True, verbose_name='Категория')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_id': self.pk})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']



class Artifact(models.Model):
    '''класс для вещи на складе
    название, краткое описание, текст, фото, дата создания, дата изменения, опубликовано, автор'''
    title = models.CharField(max_length=255, verbose_name='Название')
    summary = models.CharField(max_length=255, verbose_name='Описание')
    text = models.TextField(blank=True, verbose_name='Текст')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото', blank=True)
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    is_published = models.BooleanField(default=True, verbose_name='Публикация')
    author = models.CharField(max_length=255, verbose_name='Автор')
    cat = models.ForeignKey(Category, on_delete=models.PROTECT, null=True, verbose_name='Категория')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_id': self.pk})

    class Meta:
        verbose_name = 'Вещь'
        verbose_name_plural = 'Вещи'
        ordering = ['time_create', 'title']


class Comment(models.Model):
    user_email = models.EmailField()
    name = models.CharField('Имя', max_length=100)
    text_comments = models.TextField('Текст комментария', max_length=2000)
    post = models.ForeignKey(Artifact, on_delete=models.CASCADE, verbose_name='Публикация')

    def __str__(self):
        return f'{self.name}, {self.post}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Likes(models.Model):
    '''лайки'''
    ip = models.CharField('IP-адрес', max_length=100)
    post = models.ForeignKey(Artifact, verbose_name='Публикация', on_delete=models.CASCADE)

miniblog/stock/forms.py
from .models import *
from django import forms
from django.core.exceptions import ValidationError


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'user_email', 'text_comments')


class AddStockForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat'].empty_label = 'Категория не выбрана'

    class Meta:
        model = Artifact
        fields = ['title', 'summary', 'text', 'photo', 'is_published', 'author', 'cat']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'text': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 200:
            raise ValidationError('Длина превышает 200 символов')
        return title

miniblog/stock/views.py
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.shortcuts import render, redirect

from django.views.generic import DetailView, UpdateView, DeleteView, View
from .models import *
from .forms import *



def index(request):
    posts = Artifact.objects.all()
    context = {
        'posts': posts,
        'title': 'Главная страница',
        'cat_selected': 0,}
    return render (request, 'stock/index.html', context=context)


def about(request):
    return render (request, 'stock/about.html', { 'title': 'О сайте'})


def add_page(request):
    if request.method == 'POST':
        form = AddStockForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = AddStockForm()
    return render (request, 'stock/add_page.html', {'form': form, 'title': 'Добавить статью'})


def contact(request):
    return render (request, 'stock/contact.html', { 'title': 'Обратная связь'})

def login(request):
    return render(request, 'stock/login.html', { 'title': 'Войти'})

def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')


def show_post(request, post_id):
    art = Artifact.objects.get(id=post_id)
    context = {
        'post': art,
        'title': art,
    }
    return render(request, 'stock/one_art.html', context=context)



def show_category(request, cat_id):
    posts = Artifact.objects.filter(cat_id=cat_id)

    context = {
        'posts': posts,
        'title': 'Отображение по категориям',
        'cat_selected': cat_id, }
    return render (request, 'stock/index.html', context=context)

class AddComment(View):
    def post(self, request, post_id):
        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.post_id = post_id
                form.save()
        return redirect(f'/{post_id}')


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class AddLike(View):
    def get(self, request, post_id):
        ip_client = get_client_ip(request)
        try:
            Likes.objects.get(ip = ip_client, post_id = post_id)
            return redirect(f'/{post_id}')
        except:
            new_like = Likes()
            new_like.ip = ip_client
            new_like.post_id = int(post_id)
            new_like.save()
            return redirect(f'/{post_id}')


class DelLike(View):
    def get(self, request, post_id):
        ip_client = get_client_ip(request)
        try:
            lik = Likes.objects.get(ip = ip_client)
            lik.delete()
            return redirect(f'/{post_id}')
        except:
            return redirect(f'/{post_id}')

miniblog/stock/templates/stock/about.html
{% extends 'stock/base.html' %}

{% block content %}

    <h1>{{ title }}</h1>
<p>Содержимое страницы о сайте </p>
{% endblock %}

miniblog/stock/templates/stock/add_page.html
{% extends 'stock/base.html' %}

{% block content %}

    <h1>{{ title }}</h1>
<form action="{% url 'add_page' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <button type="submit">Добавить</button>

</form>
{% endblock %}

miniblog/stock/templates/stock/base.html
{% load static %}
{% load stock_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'stock/css/styles.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.2.1/css/all.css">

</head>
<body>
    <aside>
        <img src="{% static 'stock/images/dacha7.jpg' %}" class="image">
        <span class = "logo">Избушка</span>
        <h3>Навигация</h3>
<!--        {% get_menu as menu %}-->
        <ul>

            {% show_menu %}

        </ul>
    </aside>
{% block mainmenu %}

    <table class="table-content" border=0 cellpadding="0" cellspacing="0">
        <tr>
            <td valign="top" class="left-chapters">

                <ul id="leftchapters">

    {% if cat_selected == 0 %}
        <li>Все категории</li>
    {% else %}
        <li><a href="{% url 'home' %}">Все категории</a></li>
    {% endif %}

    {% show_categories 'name' cat_selected %}
                </ul>

            </td>
        </tr>

    </table>

    <div class="header">
        <ul id="mainmenu" class="mainmenu">
        <li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>
        </ul>
    </div>
{% endblock mainmenu %}

{% block content %}
{% endblock content %}
</body>
</html>

miniblog/stock/templates/stock/contact.html
{% extends 'stock/base.html' %}

{% block content %}

    <h1>{{ title }}</h1>
<p>Обратная связь</p>
{% endblock %}

miniblog/stock/templates/stock/index.html
{% extends 'stock/base.html' %}

{% block content %}

<ul class="list-articles">
    {% for p in posts %}
    <li>
        <h2><a href="{{ p.get_absolute_url }}"> {{p.title}}</a></h2>

        {% if p.photo %}
            <p><img class="img-article-left thumb" src="{{p.photo.url}}"></p>
        {% endif %}
        <p>{{p.text|linebreaks|truncatewords:20}}</p>
        <div class="clear"></div>


        <hr>
    </li>
    {% endfor %}
</ul>

{% endblock %}

miniblog/stock/templates/stock/list_categories.html
{% for c in cats %}
    {% if c.pk == cat_selected %}
        <li>{{c.name}}</li>
    {% else %}
        <li><a href="{{ c.get_absolute_url }}">{{c.name}}</a></li>
    {% endif %}
{% endfor %}

miniblog/stock/templates/stock/list_menu.html
  {% for m in menu %}
        {% if not forloop.last %}
            <li><i class="fa-solid fa-house"></i><a href={% url m.url_name %}>{{m.title}}</a>  </li>
        {% else %}
            <li class = 'last'><i class="fa-solid fa-house"></i><a href={% url m.url_name %}>{{m.title}}</a></li>
        {% endif %}
  {% endfor %}

miniblog/stock/templates/stock/login.html
{% extends 'stock/base.html' %}

{% block content %}

    <h1>{{ title }}</h1>
<p>Авторизация</p>
{% endblock %}

miniblog/stock/templates/stock/one_art.html
{% extends 'stock/base.html' %}

{% block content %}

<div>
    <h3>{{post.title }}</h3>
    <p><img class="img-article-left thumb" src="{{post.photo.url}}"></p>
    <p>{{post.text}}</p>
</div>

<h5><p class="link-read-post"><a href="{% url 'home' %}">Назад</a></p></h5>
<div>
    <br>
    <p>Понравилось: {{ post.likes_set.all.count }}</p>
    <br>
    <a href="{% url 'add_likes' post.id %}" class="btn btn-outline-primary">Нравится </a>
    <a href="{% url 'del_likes' post.id %}" class="btn btn-outline-danger">Не нравится</a>
</div>
<br>

<div>
    <h5>Оставить комментарий</h5>
    <div>
        <form action="{% url 'add_comment' post.id %}" method="post">
            {% csrf_token %}
            <div>
                <label>Ваш комментарий</label>
                <textarea name="text_comments"></textarea>
            </div>

            <div>
                <label>Ваше имя *</label>
                <input type="text" name="name">
            </div>

            <div>
                <label>Ваш email *</label>
                <input type="email" name="user_email">
            </div>

            <div><input type="submit"></div>

        </form>
    </div>

    <div>
        {% for comment in post.comment_set.all %}
        <div class="view-comment">
            <h4>{{ comment.name }}</h4>
            <p>
                {{ comment.text_comments }}
            </p>
        </div>

        {% endfor %}
    </div>

</div>

{% endblock %}